debian/Xsession.d/90gpg-agent etc/X11/Xsession.d
debian/systemd-environment-generator/90gpg-agent usr/lib/systemd/user-environment-generators
debian/tmp/usr/bin/gpg-agent
debian/tmp/usr/lib/gnupg/gpg-check-pattern
debian/tmp/usr/lib/gnupg/gpg-preset-passphrase
debian/tmp/usr/lib/gnupg/gpg-protect-tool
doc/examples/systemd-user/gpg-agent-browser.socket usr/lib/systemd/user
doc/examples/systemd-user/gpg-agent-extra.socket usr/lib/systemd/user
doc/examples/systemd-user/gpg-agent-ssh.socket usr/lib/systemd/user
doc/examples/systemd-user/gpg-agent.service usr/lib/systemd/user
doc/examples/systemd-user/gpg-agent.socket usr/lib/systemd/user
